// Song data for What Should I Listen To?
// Exports: songs (array)

export const songs = [
  {
    title: 'Dreams',
    artist: 'Fleetwood Mac',
    activity: 'driving',
    vibe: 'chill',
    genre: 'rock',
    durationSeconds: 257,
  },
  {
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    activity: 'party',
    vibe: 'hyped',
    genre: 'pop',
    durationSeconds: 200,
  },
  {
    title: 'Weightless',
    artist: 'Marconi Union',
    activity: 'studying',
    vibe: 'focused',
    genre: 'indie',
    durationSeconds: 505,
  },
  {
    title: 'Lose Yourself',
    artist: 'Eminem',
    activity: 'workout',
    vibe: 'hyped',
    genre: 'rap',
    durationSeconds: 326,
  },
  {
    title: 'Clair de Lune',
    artist: 'Claude Debussy',
    activity: 'relaxing',
    vibe: 'chill',
    genre: 'classical',
    durationSeconds: 300,
  },
  {
    title: 'September',
    artist: 'Earth, Wind & Fire',
    activity: 'party',
    vibe: 'upbeat',
    genre: 'pop',
    durationSeconds: 215,
  },
  {
    title: 'Take Five',
    artist: 'The Dave Brubeck Quartet',
    activity: 'studying',
    vibe: 'chill',
    genre: 'jazz',
    durationSeconds: 324,
  },
  {
    title: 'Go Your Own Way',
    artist: 'Fleetwood Mac',
    activity: 'driving',
    vibe: 'upbeat',
    genre: 'rock',
    durationSeconds: 220,
  },
  {
    title: 'Godspeed',
    artist: 'Frank Ocean',
    activity: 'sleeping',
    vibe: 'chill',
    genre: 'indie',
    durationSeconds: 232,
  },
  {
    title: 'Eye of the Tiger',
    artist: 'Survivor',
    activity: 'workout',
    vibe: 'hyped',
    genre: 'rock',
    durationSeconds: 245,
  },
  {
    title: 'Blue in Green',
    artist: 'Miles Davis',
    activity: 'relaxing',
    vibe: 'chill',
    genre: 'jazz',
    durationSeconds: 329,
  },
  {
    title: 'Bad Guy',
    artist: 'Billie Eilish',
    activity: 'driving',
    vibe: 'upbeat',
    genre: 'pop',
    durationSeconds: 194,
  },
  {
    title: 'Nocturne Op.9 No.2',
    artist: 'Chopin',
    activity: 'sleeping',
    vibe: 'chill',
    genre: 'classical',
    durationSeconds: 270,
  },
  {
    title: 'Can’t Stop',
    artist: 'Red Hot Chili Peppers',
    activity: 'workout',
    vibe: 'upbeat',
    genre: 'rock',
    durationSeconds: 269,
  },
  {
    title: 'Youngblood',
    artist: '5 Seconds of Summer',
    activity: 'party',
    vibe: 'upbeat',
    genre: 'pop',
    durationSeconds: 203,
  },
  {
    title: 'Space Song',
    artist: 'Beach House',
    activity: 'studying',
    vibe: 'chill',
    genre: 'indie',
    durationSeconds: 322,
  },
  {
    title: 'Juicy',
    artist: 'Notorious B.I.G.',
    activity: 'party',
    vibe: 'hyped',
    genre: 'rap',
    durationSeconds: 300,
  },
  {
    title: 'River Flows in You',
    artist: 'Yiruma',
    activity: 'relaxing',
    vibe: 'chill',
    genre: 'classical',
    durationSeconds: 183,
  },
  {
    title: 'Sunflower',
    artist: 'Post Malone & Swae Lee',
    activity: 'driving',
    vibe: 'chill',
    genre: 'rap',
    durationSeconds: 158,
  },
  {
    title: 'Holocene',
    artist: 'Bon Iver',
    activity: 'relaxing',
    vibe: 'focused',
    genre: 'indie',
    durationSeconds: 330,
  },
];
